### ISSUE TITLE
Running into a deadlock error when bulk deleting not found errors

### ISSUE THREAD

**Issue by jaandrews** [Infocaster/UrlTracker#134] opened 2023-06-09 23:04 UTC
**Describe the bug**
_Using version: 10.3.0
When I attempted to delete multiple not found errors at once, I get the following error for each entry it tries to delete.
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Transaction (Process ID 77) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String methodName)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at StackExchange.Profiling.Data.ProfiledDbCommand.ExecuteNonQuery() in C:\projects\dotnet\src\MiniProfiler.Shared\Data\ProfiledDbCommand.cs:line 300
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<ExecuteNonQuery>b__32_0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.<>c__DisplayClass38_0`1.<Execute>b__0()
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.RetryPolicy.ExecuteAction[TResult](Func`1 func)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.Execute[T](Func`1 f)
   at Umbraco.Cms.Infrastructure.Persistence.FaultHandling.FaultHandlingDbCommand.ExecuteNonQuery()
   at NPoco.Database.<>c__DisplayClass296_0.<ExecuteNonQueryHelper>b__0()
   at NPoco.Database.ExecutionHook[T](Func`1 action)
   at NPoco.Database.ExecuteNonQueryHelper(DbCommand cmd)
   at NPoco.Database.Execute(String sql, CommandType commandType, Object[] args)
   at NPoco.Database.Execute(Sql Sql)
   at NPoco.Database.Execute(String sql, Object[] args)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.PersistDeletedItem(TEntity entity)
   at Umbraco.Cms.Core.Cache.DefaultRepositoryCachePolicy`2.Delete(TEntity entity, Action`1 persistDeleted)
   at Umbraco.Cms.Infrastructure.Persistence.Repositories.Implement.EntityRepositoryBase`2.Delete(TEntity entity)
   at UrlTracker.Core.Database.ClientErrorRepository.Delete(IClientError entity)
   at UrlTracker.Core.ClientErrorService.DeleteAsync(ClientError ClientError)
   at UrlTracker.Backoffice.UI.Controllers.UrlTrackerManagerController.DeleteEntry(DeleteEntryRequest request)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
ClientConnectionId:6c910ade-8dc5-4192-9643-475ba3a6f753
Error Number:1205,State:51,Class:13
ClientConnectionId before routing:f866c008-27a9-4d29-9468-faea3de0d379
Routing Destination:ab71f5243fd1.tr19251.eastus2-a.worker.database.windows.net,11023
```

**To Reproduce**
1. Visit some non existent pages to generate not found entries.
2. Go to the "Not founds" section in the UrlTracker tab.
3. Click the checkbox in the upper left corner to select the first 20 not found issues.
4. Click the delete button in the upper right corner.

**Expected behavior**
All of the entries are deleted successfully

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome 114

**Additional context**
This error doesn't happen when deleting the entries with the trash can button on the right side of each entry. It only happens for the bulk operation, even when I only select one entry to delete.

**Comment by D-Inventor** [comment] 2023-06-10 07:45
Thanks a lot for your detailed bug report! I'll look into it and come back to you when I have an update. That should be somewhere in the next two days.

**Comment by SimonAntony** [comment] 2023-06-14 10:47
Concur i'm seeing the same - problem is I have 55k records to delete so this is a really slow way to do it. Is there an SQL option I can run in the meantime to just clear out the not founds?

**Comment by jaandrews** [comment] 2023-06-14 17:39
@SimonAntony You'll want to backup your database before this just in case, but I was able to clear it with "DELETE FROM [dbo].[urltrackerClientError]," as redirects are stored in a different table. You may need to run "DELETE FROM [dbo].[urltrackerClientError2Referrer]" first though, since it has dependencies on the client error ids.

**Comment by D-Inventor** [comment] 2023-06-17 16:21
I can confirm that above SQL statements correctly clear the Not Found records and only the first command should be necessary as all records in the `[urltrackerClientError2Referrer]` table should automatically disappear when the related row in the foreign key is deleted.

I unfortunately haven't been able to look into this issue yet as I've been very occupied this week, but this issue hasn't fallen off my radar, I will be looking into this as soon as I can.

**Comment by D-Inventor** [comment] 2023-06-18 14:43
I've tried out the bulk delete feature, but have not been able to reproduce this behaviour.

@jaandrews @SimonAntony Could you tell me something about the hosting environment? In particular, are you hosting your database and/or your application in Azure or a similar cloud platform?

**Comment by SimonAntony** [comment] 2023-06-19 07:47
@D-Inventor Hi - yes this particular site is on Azure, we have it load balanced so an admin side and front end side. Cant reproduce locally either, only happens on live and I don't have access to that DB either so can't even investigate further :(

**Comment by jaandrews** [comment] 2023-06-19 16:07
@D-Inventor I run into it in azure (not load balanced) and my local environment. In my local environment, it did work the first time, but when I attempted to delete a second batch, I encountered the error I originally reported.

**Comment by D-Inventor** [comment] 2024-05-24 15:10
I released an alpha version of the URL Tracker for Umbraco 10 and 13 today. It has a fix for this issue. However, this version contains a lot of major changes, so it may not be a matter of "just update" at the moment. I do encourage you to give it a try, but make sure to backup your database before you update.

**Comment by D-Inventor** [comment] 2024-10-09 04:17
In version 13.2.0, bulk operations have been optimized and this issue should no longer occur. I'm closing this issue.

**Closed as completed by D-Inventor** 2024-10-09 04:17 UTC
Labels: bug
