### ISSUE TITLE
UrlTracker - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by RefaelAzari** [Infocaster/UrlTracker#40] opened 2022-06-07 09:03 UTC
**Describe the bug**
_Using version: Umbraco 9.5 rc2\9.5.1 .Net Core_
i installed UrlTracker v9 and configured as documanted  and i getting NullReferenceException: Object reference not set to an instance of an object.

**To Reproduce**
1. install UrlTracker from nuget 
2. Startup.cs:
public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseUmbraco()
                .WithMiddleware(u =>
                {
                    u.UseBackOffice();
                    u.UseWebsite();
                    u.UseUrlTracker();
                })
                .WithEndpoints(u =>
                {
                    u.UseInstallerEndpoints();
                    u.UseBackOfficeEndpoints();
                    u.UseWebsiteEndpoints();
                });
        }
4. build
5. See error

**Expected behavior**
NullReferenceException: Object reference not set to an instance of an object.
UrlTracker.Core.Intercepting.Preprocessing.DomainUrlPreprocessor+<>c__DisplayClass2_0.<PreprocessUrlAsync>b__0(Domain d)
System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate, out bool found)
System.Linq.Enumerable.FirstOrDefault<TSource>(IEnumerable<TSource> source, Func<TSource, bool> predicate)
UrlTracker.Core.Intercepting.Preprocessing.DomainUrlPreprocessor.PreprocessUrlAsync(Url url, IInterceptContext context)
UrlTracker.Core.Intercepting.Preprocessing.InterceptPreprocessorCollection.PreprocessUrlAsync(Url url, IInterceptContext context)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
UrlTracker.Core.Intercepting.IntermediateInterceptService.GetAsync(Url url, IInterceptContext context)
UrlTracker.Core.Caching.TypedMemoryCache<TKey, TValue>.ExecuteFactory(Func<Task<TValue>> factory, CancellationTokenSource cts)
UrlTracker.Core.InterceptService.GetAsync(Url url)
UrlTracker.Web.UrlTrackerMiddleware.DoInterceptAsync(HttpContext context, Url url)
UrlTracker.Web.UrlTrackerMiddleware.InvokeAsync(HttpContext context)
Umbraco.Cms.Web.Common.Middleware.BasicAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.BackOffice.Middleware.BackOfficeExternalLoginProviderErrorMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in MiniProfilerMiddleware.cs
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
Microsoft.AspNetCore.Builder.UseMiddlewareExtensions+<>c__DisplayClass6_1+<<UseMiddlewareInterface>b__1>d.MoveNext()
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by D-Inventor** [comment] 2022-06-07 09:52
Hi RefaelAzari,

Thank you very much for your report! I would like to ask you a few questions:
  - Is there a pending Umbraco update / install in your setup? I've noticed that this is an issue and a fix for this has been implemented, though release of this fix is still pending.
  - If yes, could you try finishing the Umbraco update / install without the URL Tracker middleware and then reapply the middleware? If that works, that could be a temporary workaround.
  - If no,  could you share or describe the url on which you call your website? The error points to a line where an assumption is made that each url has a host and a path (a root url should have a `/` for a path). 
  - Do you have any domains configured in umbraco on any nodes and if so: can you share or describe the domains that you have configured?

**Comment by RefaelAzari** [comment] 2022-06-07 14:32
when i removed the domains it works but i need them, what can i do?

‫בתאריך יום ג׳, 7 ביוני 2022 ב-17:22 מאת רפאל אזערי ***@***.***‬‏>:‬

**Comment by D-Inventor** [comment] 2022-06-07 14:57
I have a hunch, what the issue might be. I think the domains that you defined in umbraco have no hostname. As a temporary workaround, you could try to include a hostname in your umbraco domain. So instead of writing `/en`, you write `my.domain.com/en` or `https://my.domain.com/en`.

The URL Tracker is supposed to support any domain format in Umbraco though, so this is definitely a bug. I'll see if I can reproduce this issue and then I'll get back to you!

**Comment by RefaelAzari** [comment] 2022-06-07 15:34
Awesome, thanks! it works great now

‫בתאריך יום ג׳, 7 ביוני 2022 ב-17:57 מאת ‪Dennis‬‏ <‪
***@***.***‬‏>:‬

**Comment by D-Inventor** [comment] 2022-06-07 16:27
I have been able to reproduce this issue. Since there's a decent workaround for it and the solution is trivial, I've marked it as a 'good first issue', so somebody can pick it up if they want. It'll be fixed in the next big release.

The issue is that the DomainUrlPreprocessor class assumes that every domain has a hostname. This is not always the case. If the domain does not have a hostname, the check should not compare against the hostname.

**Comment by RefaelAzari** [comment] 2022-06-08 13:06
Awesome, thanks for the update!

‫בתאריך יום ג׳, 7 ביוני 2022 ב-19:27 מאת ‪Dennis‬‏ <‪
***@***.***‬‏>:‬

**Comment by D-Inventor** [comment] 2022-07-01 06:04
There's a related issue with a problem in the same piece of code. It has boosted the urgency for this issue, so I'll be posting a fix soon (probably somewhere today)

**Comment by D-Inventor** [comment] 2022-07-01 07:31
[Version 9.0.2-beta0002](https://www.nuget.org/packages/UrlTracker/9.0.2-beta0002) should fix this issue. Do you have a chance to give it a try?

**Closed as completed** 2022-07-02 11:36 UTC
Labels: bug, v9, feedback wanted, v10
