### ISSUE TITLE
Umbraco 10.   Url Tracker overwriting other packages settings node

### ISSUE THREAD

**Issue by pgregorynz** [Infocaster/UrlTracker#69] opened 2022-08-29 04:27 UTC
**Describe the bug**
_Using version: 10.1.0

We have both Vendr and Url Tracker in our Umbraco 10.1.0 project.  UrlTracker is overwriting the Vendr settings item in the Settings tree. (see screenshot)

**To Reproduce**
1. Install Vendr (this is the package we have observed this behaviour in)
2. Install Url Tracker
3. Go to settings
4. See error.  Store Settings under the Commerce node is replace with UrlTracker settings.

**Expected behavior**
UrlTracker needs to check which root node that it is attaching its node to in the tree.

**Screenshots**

![image](https://user-images.githubusercontent.com/1634892/187122872-4e32c6f1-e994-4006-8fca-60cd7b174cca.png)

**Comment by D-Inventor** [comment] 2022-08-29 04:54
Hi @pgregorynz ! Thank you very much for reporting this issue. I'll see if I can reproduce this and if I can find out what the cause is and then I'll get back to you either later today or tomorrow.

**Comment by D-Inventor** [comment] 2022-08-29 06:09
I have been able to reproduce this issue, but I haven't found the cause of this issue yet. I'll keep looking and will post an update when I have found something

**Comment by pgregorynz** [comment] 2022-08-29 12:22
Hi @D-Inventor for some reason the following gets run twice, and ignores anything you have in the Tree directive.

`protected override ActionResult<TreeNode?> CreateRootNode(FormCollection queryStrings)`

not sure if this helps track it down.

**Comment by D-Inventor** [comment] 2022-08-29 14:58
You are right, it does appear to be executed twice, but I'm not sure why. I've compared the tree controller with the umbraco documentation and they look the same, so I'm wondering if perhaps this is an issue with Vendr or Umbraco? Other trees in the settings section appear unaffected.

**Comment by D-Inventor** [comment] 2022-08-29 16:04
I've found a solution to the problem. There seems to be a naming conflict between the tree controllers of Vendr and the URL Tracker. Renaming the controller in the URL Tracker solves this issue, though it should probably also be reported to Umbraco, because I don't think this is intended behaviour.

I'll release a beta version tomorrow with the fix, so you can give it a try yourself

**Comment by pgregorynz** [comment] 2022-08-29 21:32
Thanks for getting onto this so quickly!  We will give it a spin.

**Comment by D-Inventor** [comment] 2022-08-30 08:25
I just released [10.1.1-beta.1](https://www.nuget.org/packages/UrlTracker/10.1.1-beta0001). Could you please confirm that the issue is fixed with this new version?

**Comment by D-Inventor** [comment] 2022-09-06 12:32
Hi @pgregorynz ! It's been a week since the last activity on this issue. Have you been able to try out the new beta release? I'd love to hear your feedback!

**Comment by D-Inventor** [comment] 2022-09-15 15:04
I've released [version 10.1.1](https://www.nuget.org/packages/UrlTracker/10.1.1) with a fix. I'm closing the issue.

If the problem persists, please reopen the issue with additional information.

**Closed as completed** 2022-09-17 08:06 UTC
Labels: bug, feedback wanted
